# .streamlit/secrets.toml

[connections.snowflake]
account = "sb98932.us-east-2.aws"
user = "dhanush_poc"
password = "Poc@12345"
role = "POC_DEVELOPER"
warehouse = "POC_WH"
database = "POC_DB"
schema = "POC_SCHEMA"
client_session_keep_alive = true
